# Generated by Django 4.2 on 2024-11-19 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TournamentApp', '0002_tournamentequipment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TournamentEquipment',
        ),
    ]
