# Generated by Django 4.2 on 2024-11-20 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipmentApp', '0002_supplier_alter_equipment_options_and_more'),
        ('TournamentApp', '0003_delete_tournamentequipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, help_text='Quantity of this equipment for the tournament')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipmentApp.equipment')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TournamentApp.tournament')),
            ],
        ),
    ]
