# Generated by Django 4.2 on 2024-11-04 19:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only letters are allowed.')])),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$', 'Invalid email format.')])),
                ('address', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]*$', 'Only letters and numbers are allowed.')])),
                ('website', models.URLField(validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9]*$', 'Only letters and numbers are allowed.')])),
                ('type', models.CharField(choices=[('corporate', 'corporate'), ('small business', 'small business'), ('governmental', 'governmental')], max_length=100)),
            ],
        ),
    ]
