# Generated by Django 5.0.7 on 2024-10-27 08:11

import django.core.validators
import gamesman.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamesman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='File_Size',
            field=models.CharField(max_length=20, validators=[gamesman.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='game',
            name='Game_Title',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='Genre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='game',
            name='Nb_Players',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='game',
            name='Platform',
            field=models.CharField(max_length=50),
        ),
    ]
