# Generated by Django 5.0.7 on 2024-10-27 08:51

import django.core.validators
import gamesman.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamesman', '0002_alter_game_file_size_alter_game_game_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Game_Title', models.CharField(max_length=100)),
                ('Genre', models.CharField(max_length=50)),
                ('Platform', models.CharField(max_length=50)),
                ('Release_Date', models.DateField()),
                ('Developer', models.CharField(max_length=100)),
                ('Publisher', models.CharField(max_length=100)),
                ('Nb_Players', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('File_Size', models.CharField(max_length=20, validators=[gamesman.models.validate_file_size])),
            ],
        ),
    ]
