# Generated by Django 4.2 on 2024-11-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamesman', '0003_suggestedgame'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuggestedGame',
        ),
        migrations.RemoveField(
            model_name='game',
            name='id',
        ),
        migrations.AlterField(
            model_name='game',
            name='Game_Title',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
