# Generated by Django 4.2 on 2024-11-04 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sponsorApp', '0002_alter_sponsor_website'),
        ('TournamentApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sponsorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('terminated', 'Terminated')], max_length=20)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sponsorApp.sponsor')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TournamentApp.tournament')),
            ],
        ),
    ]
