# Generated by Django 4.2 on 2024-11-11 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SponsorshipApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorship',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Terminated', 'Terminated')], max_length=20),
        ),
    ]
