# Generated by Django 4.2 on 2024-11-23 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0004_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Sponsor', 'Sponsor'), ('Player', 'Player'), ('TournamentAdmin', 'TournamentAdmin')], max_length=255, verbose_name='role'),
        ),
    ]
