# Generated by Django 4.2 on 2024-11-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Sponsor', 'Sponsor'), ('Player', 'Player'), ('TournamentAdmin', 'TournamentAdmin'), ('GamesAdmin', 'GamesAdmin')], max_length=255, verbose_name='role'),
        ),
    ]
