# Generated by Django 4.2 on 2024-11-11 22:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TournamentApp', '0001_initial'),
        ('Participation', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together={('participant', 'tournament')},
        ),
    ]
