# Generated by Django 4.2 on 2024-11-17 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Participation', '0003_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='participation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='Participation.participation'),
        ),
    ]
